export const actionTypes = {
    PRODUCT_REQUEST: 'PRODUCT_REQUEST',
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCT : 'SELECTED_PRODUCTS',
    REMOVE_PRODUCT : 'REMOVE_PRODUCTS',
    PRODUCT_ERROR : 'PRODUCT_ERROR'
}